apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./kafka-compose.yaml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
      matchLabels:
        name: kafka-1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./kafka-compose.yaml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-1
        name: kafka-1
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://10.252.94.73:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: confluentinc/cp-kafka:5.1.0
        name: kafka-1
        terminationMessagePath: "/Users/Killjoy/Docker/kafka-compose-results/tmp/my-log"
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
