export const REQUEST_BATTLEFIELDS = 'REQUEST_BATTLEFIELDS';
export const RECEIVE_BATTLEFIELDS = 'RECEIVE_BATTLEFIELDS';
export const REQUEST_BATTLEFIELD = 'REQUEST_BATTLEFIELD';
export const RECEIVE_BATTLEFIELD = 'RECEIVE_BATTLEFIELD';
