export const TOGGLE_CHARACTER = 'TOGGLE_CHARACTER';
export const SELECT_MAP = 'SELECT_MAP';
export const SELECT_ENEMY = 'SELECT_ENEMY';
export const REQUEST_CREATE_BATTLE = 'REQUEST_CREATE_BATTLE';
export const RECEIVE_CREATE_BATTLE = 'RECEIVE_CREATE_BATTLE';
