export const REQUEST_CHARACTER = 'REQUEST_CHARACTER';
export const RECEIVE_CHARACTER = 'RECEIVE_CHARACTER';

export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';

export const REQUEST_CREATE_CHARACTER = 'REQUEST_CREATE_CHARACTER';
export const RECEIVE_CREATE_CHARACTER = 'RECEIVE_CREATE_CHARACTER';

export const REQUEST_DELETE_CHARACTER = 'REQUEST_DELETE_CHARACTER';
export const RECEIVE_DELETE_CHARACTER = 'RECEIVE_DELETE_CHARACTER';
