export const REQUEST_MAP = 'REQUEST_MAP';
export const RECEIVE_MAP = 'RECEIVE_MAP';

export const REQUEST_MAPS = 'REQUEST_MAPS';
export const RECEIVE_MAPS = 'RECEIVE_MAPS';

export const REQUEST_CREATE_MAP = 'REQUEST_CREATE_MAP';
export const RECEIVE_CREATE_MAP = 'RECEIVE_CREATE_MAP';

export const REQUEST_DELETE_MAP = 'REQUEST_DELETE_MAP';
export const RECEIVE_DELETE_MAP = 'RECEIVE_DELETE_MAP';
